### PR TITLE
RD-4921 dispatch: reduce import overhead

### PR DESCRIPTION
**Pull request by tehasdf**
Only conditionally import some things.
See commits separately, each explains a specific thing.

### CODE REVIEW

**Review by mateumann — APPROVED** [review]

**Review by geokala — APPROVED** [review]
Have you looked to see how much memory usage improvement this provides?

**Comment by tehasdf** [comment]
> Have you looked to see how much memory usage improvement this provides?

It's hard to measure consistently, but 10MB (~16%) at least. Depending on which scenario. But I was mostly interested in the upload_blueprint workflow, in which we now avoid importing 1) uuid, 2) pika, 3) jinja2

**Comment by tehasdf** [comment]
FWIW benchmarks, the `test_thousand_deployments` benchmark goes from ~12:50 to ~11:20 with this, and the `test_deploy_multi_large_scale` from ~4:50 to ~4:10

**Comment by geokala** [comment]
Nice.

**Review by geokala — DISMISSED** [review]

**Review by geokala — APPROVED** [review]

**Review by mateumann — APPROVED** [review]

**Pull request merged**
